# Generated by Django 5.0.3 on 2024-03-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_size_id_product_sub_category_id'),
        ('sales', '0001_initial'),
        ('user', '0007_customer_company_id_supplier_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_status',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale_return_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesreturn')),
            ],
        ),
    ]
