# Generated by Django 5.0.2 on 2024-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_customer_id_alter_sales_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='salesdetails',
            options={'verbose_name': 'Sale Details', 'verbose_name_plural': 'Sale Details'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'verbose_name': 'Sale Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AlterModelOptions(
            name='salesreturndetails',
            options={'verbose_name': 'Sales Return Detail', 'verbose_name_plural': 'Sales Return Details'},
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
