# Generated by Django 5.0.3 on 2024-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qoh', models.IntegerField()),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('fabric', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
