# Generated by Django 5.0.3 on 2024-03-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default=False,
        ),
    ]
