# Generated by Django 5.0.3 on 2024-05-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isCarousel',
            field=models.BooleanField(default=False),
        ),
    ]
