# Generated by Django 5.0.2 on 2024-06-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_iscarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
