# Generated by Django 5.0.3 on 2024-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.BooleanField(null=True),
        ),
    ]
