# Generated by Django 5.0.2 on 2024-06-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customer_options_alter_supplier_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_id',
        ),
    ]
