# Generated by Django 5.0.2 on 2024-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_area_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
